// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE1OLT5VrDrNspEOdHbTRi5Es2c2oHT4k',
    appId: '1:1022786040381:web:3c8c8029f42ab278253054',
    messagingSenderId: '1022786040381',
    projectId: 'sdn-project-b76b3',
    authDomain: 'sdn-project-b76b3.firebaseapp.com',
    storageBucket: 'sdn-project-b76b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXj1wX7lP5zTchaf3mCsjA7Dnd8Yu7fFg',
    appId: '1:1022786040381:android:cd46c7aba62a153a253054',
    messagingSenderId: '1022786040381',
    projectId: 'sdn-project-b76b3',
    storageBucket: 'sdn-project-b76b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmkk7jDZVng2XzvdoceuX8Yi6Wn-uEgh0',
    appId: '1:1022786040381:ios:e1d72265c1ba90aa253054',
    messagingSenderId: '1022786040381',
    projectId: 'sdn-project-b76b3',
    storageBucket: 'sdn-project-b76b3.appspot.com',
    iosBundleId: 'com.example.loginRegisterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmkk7jDZVng2XzvdoceuX8Yi6Wn-uEgh0',
    appId: '1:1022786040381:ios:e1d72265c1ba90aa253054',
    messagingSenderId: '1022786040381',
    projectId: 'sdn-project-b76b3',
    storageBucket: 'sdn-project-b76b3.appspot.com',
    iosBundleId: 'com.example.loginRegisterApp',
  );
}
